version: '3.8'
services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - opensearch
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
      OPENSEARCH_HOST: "opensearch"
      OPENSEARCH_PORT: "9200"
      OPENSEARCH_SCHEME: "http"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_AMQP_DESERIALIZATION_TRUST_ALL: "true"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # AMQP 포트
      - "15672:15672"  # 관리 콘솔 포트
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:2.3.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
      - "9600:9600"

volumes:
  mysql_data:
