spring:
  datasource:
    url: "jdbc:mysql://mysql:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    baseline-on-migrate: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: guest
    password: guest

  amqp:
    deserialization:
      trust:
        all: true

# docker-compose ? opensearch ???? ?? ??
opensearch:
  host: opensearch
  port: 9200
  scheme: http

logging:
  level:
    org.springframework: INFO
