spring:
  datasource:
    # docker-compose ?? mysql ???? ??? ???? ??
    url: jdbc:mysql://mysql:3306/ecommerce?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# docker-compose ? opensearch ???? ?? ??
opensearch:
  host: opensearch
  port: 9200
  scheme: http

logging:
  level:
    org.springframework: INFO
